// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendSmart.Category.API.Data;

#nullable disable

namespace SpendSmart.Category.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425182220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpendSmart.Category.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Color = "#FF6B6B",
                            Icon = "🍕",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Food",
                            Type = "Expense",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 2,
                            Color = "#4ECDC4",
                            Icon = "🚗",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Transport",
                            Type = "Expense",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 3,
                            Color = "#45B7D1",
                            Icon = "🏠",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Housing",
                            Type = "Expense",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 4,
                            Color = "#96CEB4",
                            Icon = "🏥",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Health",
                            Type = "Expense",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 5,
                            Color = "#FFEAA7",
                            Icon = "🎬",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Entertainment",
                            Type = "Expense",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 6,
                            Color = "#DDA15E",
                            Icon = "🛍️",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Shopping",
                            Type = "Expense",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 7,
                            Color = "#BC6C25",
                            Icon = "📚",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Education",
                            Type = "Expense",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 8,
                            Color = "#2ECC71",
                            Icon = "💰",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Savings",
                            Type = "Expense",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 9,
                            Color = "#3498DB",
                            Icon = "💼",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Salary",
                            Type = "Income",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 10,
                            Color = "#9B59B6",
                            Icon = "💻",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Freelance",
                            Type = "Income",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 11,
                            Color = "#E74C3C",
                            Icon = "📈",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Investment",
                            Type = "Income",
                            UserId = 0
                        },
                        new
                        {
                            CategoryId = 12,
                            Color = "#F39C12",
                            Icon = "🎁",
                            IsActive = true,
                            IsDefault = true,
                            Name = "Bonus",
                            Type = "Income",
                            UserId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
